# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NetworkModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NetworkModule
  pod 'Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :tag => '4.1.0'

end
